import { Roboto } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Layout/Header";
import { Footer } from "@/components/Layout/Footer";
import { AuthProvider } from "@/app/Providers";
import { Toaster } from "react-hot-toast";

const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "500"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-7xl mx-auto px-4">
          <AuthProvider>
            <Toaster />
            <Header />
            {children}
            <Footer />
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
